### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by sergei-sh** [kailashbuki/fingerprint#1]
> > > fpg = FingerprintGenerator(input_string='asdfsdfasfadafafadsadfa')
> > > fpg.generate_fingerprints()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/serj/work/mirror0/virtual_env/local/lib/python2.7/site-packages/fingerprint/fingerprintgenerator.py", line 151, in generate_fingerprints
> > >     self.generate_rollinghash()
> > >   File "/home/serj/work/mirror0/virtual_env/local/lib/python2.7/site-packages/fingerprint/fingerprintgenerator.py", line 81, in generate_rollinghash
> > >     prev_hash_value += ord(first_kgram[i])_(BASE_*(KLENGTH-1-i))
> > > IndexError: string index out of range
> > > exit()

**Comment by kailashbuki** [comment]
I believe that happens when you have a piece of text with less than 50 characters as the default window parameter is 50. 

I hope to rewrite the library in coming days to make it faster and bug-free. I wrote the library seven years ago when I was still learning python and playing with the winnowing algorithm. For now, you have to bear with the bugs.
